CoreDomain\Model\Project\Project:
    exclusion_policy: ALL
    properties:
        id:
            type: integer
            groups:
                - api_project_get
                - api_project_search
        title:
            type: string
            groups:
                - api_project_get
                - api_project_search
        description:
            type: string
            groups:
                - api_project_get
                - api_project_search
        code:
            type: string
            groups:
                - api_project_get
                - api_project_search