---
- name: Add ppa Repository
  become: yes
  apt_repository: repo=ppa:ondrej/php
  when: ansible_distribution == 'Ubuntu'

- name: Update apt
  become: yes
  apt: update_cache=yes

- name: Install php5
  become: yes
  apt: pkg=php5.6

#- name: Install php5-fpm
#  become: yes
#  apt: pkg=php5-fpm state=latest

- name: Install PHP Packages
  become: yes
  apt: pkg={{ item }}
  with_items: php.packages
  when: php.packages is defined

- name: Enabled php 5.6
  become: yes
  file:
    src=/usr/bin/php5.6
    dest=/etc/alternatives/php
    force=yes
    mode="u=rw,g=r,o=r"

- include: configure.yml
- include: pecl.yml
