---
- name: Set permissions on socket - owner
  become: true
  lineinfile: "dest=/etc/php5/fpm/pool.d/www.conf state=present regexp='^;?listen.owner' line='listen.owner = www-data'"

- name: Set permissions on socket - group
  become: true
  lineinfile: "dest=/etc/php5/fpm/pool.d/www.conf state=present regexp='^;?listen.group' line='listen.group = www-data'"

- name: Set permissions on socket - mode
  become: true
  lineinfile: "dest=/etc/php5/fpm/pool.d/www.conf state=present regexp='^;?listen.mode' line='listen.mode = 0660'"
  notify: restart php5-fpm

- name: ensure timezone is set in fpm php.ini
  become: true
  lineinfile: dest=/etc/php5/fpm/php.ini
              regexp='date.timezone ='
              line='date.timezone = {{ server.timezone }}'
- name: enabling opcache
  become: true
  lineinfile: dest=/etc/php5/fpm/php.ini
              regexp=';opcache.enable=0'
              line='opcache.enable=1'