---
- name: ensure timezone is set in cli php.ini
  become: true
  lineinfile: dest=/etc/php/5.6/cli/php.ini
              regexp='date.timezone ='
              line='date.timezone = {{ server.timezone }}'

- name: enabling opcache cli
  become: true
  lineinfile: dest=/etc/php/5.6/cli/php.ini
              regexp=';opcache.enable_cli=0'
              line='opcache.enable_cli=1'