CoreDomain\DTO\Project\ProjectDTO:
    exclusion_policy: ALL
    properties:
        title:
            type: string
            groups: [api_project_create, api_project_update]
        description:
            type: string
            groups: [api_project_create, api_project_update]
        code:
            type: string
            groups: [api_project_create, api_project_update]