app_project:
    resource: AppBundle\Controller\Project\ProjectController
    type: rest
    name_prefix: project_

app_user:
    resource: AppBundle\Controller\User\UserController
    type: rest
    name_prefix: user_

app_session:
    resource: AppBundle\Controller\User\UserSessionController
    type: rest
    name_prefix: session_
