---
- name: Install xDebug
  become: true
  apt: pkg=php5.6-xdebug state=latest

- name: Configure xDebug
  become: true
  template: src=xdebug.ini.j2 dest=/etc/php/5.6/mods-available/xdebug.ini owner=root group=root mode=0644

- name: activate cli xdebug
  become: true
  file: src=/etc/php/5.6/mods-available/xdebug.ini dest=/etc/php/5.6/cli/conf.d/20-xdebug.ini state=link

- name: activate fpm xdebug
  become: true
  file: src=/etc/php/5.6/mods-available/xdebug.ini dest=/etc/php/5.6/fpm/conf.d/20-xdebug.ini state=link
  notify:
    - restart php5.6-fpm